models/Clients.php
<?php

namespace app\models;

use Yii;
use app\models\Languages;
use app\models\Countries;
use app\library\Validator;
use app\library\Utils;
use yii\imagine\Image;
use Imagine\Image\Box;
use yii\web\UploadedFile;

/**
 * This is the model class for table "clients".
 *
 * @property int $id
 * @property int $referrer_id
 * @property string $login
 * @property string $first_name
 * @property string $second_name
 * @property string $last_name
 * @property string $birth_day
 * @property string $email
 * @property string $phone
 * @property string $photo
 * @property string $site
 * @property string $organization_link
 * @property string $gender
 * @property int $country_id
 * @property string $city
 * @property string $description
 * @property string $lang
 * @property string $status
 * @property int $create_timestamp
 * @property int $deleted
 */
class Clients extends AbstractCommonDb
{
    public $object_name = 'Client {id}';
    
    public static $statuses = [
        'ACTIVE' => 'Активный',
        'BANNED' => 'Забаненный',
    ];
    
    public static $genders = [
        'MALE' => 'Мужчина',
        'FTMALE' => 'Женщина',
        'OTHER' => 'Другое',
    ];
    
    public static $photo_path = '/web/images/clients/';
    public static $photo_size = [
        1500,
        1500,
    ];
    
    public static $login_rules = [
        'regexp' => '/^([a-zA-Z0-9_\-\.]{2,16})$/',
        'min_chars' => 2,
        'max_chars' => 16,
    ];
    
    public static $password_rules = [
        'min_chars' => 5,
        'max_chars' => 12,
    ];
    
    public static $name_rules = [
        'regexp' => '/^([^\d@#\$%\^&\*\(\)\[\]:;\'",\._\+]{2,50})$/',
        'min_chars' => 2,
        'max_chars' => 50,
    ];
    
    public static $city_rules = [
        'regexp' => '/^([^@#\$%\^&\*\(\)\[\]:;\'",\._\+]{2,50})$/',
        'min_chars' => 2,
        'max_chars' => 50,
    ];
    
    public static $description_rules = [
        'min_chars' => 10,
        'max_chars' => 10000,
    ];
    
    public static $available_image_extensions = [
        'jpg',
        'jpeg',
        'gif',
        'png',
    ];
    public static $max_image_size = 5000000; //  5 mb
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clients';
    }
    
    public static function attributeStaticLabels()
    {
        return [
            'id' => 'ID',
            'referrer_id' => Yii::t('app', 'Реферрер'),
            'login' => Yii::t('app', 'Никнейм'),
            'password' => Yii::t('app', 'Пароль'),
            'password_confirm' => Yii::t('app', 'Подтверждение пароля'),
            'first_name' => Yii::t('app', 'Имя'),
            'second_name' => Yii::t('app', 'Отчество'),
            'last_name' => Yii::t('app', 'Фамилия'),
            'birth_day' => Yii::t('app', 'Дата рождения'),
            'email' => Yii::t('app', 'E-mail'),
            'phone' => Yii::t('app', 'Номер телефона'),
            'photo' => Yii::t('app', 'Фотография'),
            'site' => Yii::t('app', 'Вебсайт'),
            'organization_link' => Yii::t('app', 'Ссылка на место работы'),
            'gender' => Yii::t('app', 'Пол'),
            'country_id' => Yii::t('app', 'Страна'),
            'city' => Yii::t('app', 'Город'),
            'description' => Yii::t('app', 'О себе'),
            'lang' => Yii::t('app', 'Язык'),
            'status' => Yii::t('app', 'Статус'),
            'create_timestamp' => Yii::t('app', 'Время создания'),
            'deleted' => 'Deleted',
        ];
    }
    
    public function getReferrer()
    {
        return $this->hasOne(
            self::className(), 
            ['id' => 'referrer_id']
        );
    }
    
    public function getLanguage()
    {
        return $this->hasOne(
            Languages::className(), 
            ['code' => 'lang']
        );
    }
    
    public function getCountry()
    {
        return $this->hasOne(
            Countries::className(), 
            ['id' => 'country_id']
        );
    }
    
    public function getFilterCallbacks()
    {
        return [
            'keyword' => function($filter) {
                $fields = [
                    'login',
                    'first_name',
                    'second_name',
                    'last_name',
                    'email',
                    'phone',
                    'site',
                    'organization_link',
                    'city',
                    'description',
                ];
                $where = [
                    'conditions' => "(" . implode(" ILIKE :keyword OR ", $fields) . " ILIKE :keyword)",
                    'binds' => [':keyword' => '%' . $filter . '%']
                ];
                
                return $where;
            },
            'timestamp_range_from' => function($filter) {
                $where = [
                    'conditions' => self::tableName() . ".create_timestamp >= :create_timestamp_from",
                    'binds' => [':create_timestamp_from' => strtotime($filter . ' 00:00:00')]
                ];
                return $where;
            },
            'timestamp_range_to' => function($filter) {
                $where = [
                    'conditions' => self::tableName() . ".create_timestamp <= :create_timestamp_to",
                    'binds' => [':create_timestamp_to' => strtotime($filter . ' 23:59:59')]
                ];
                return $where;
            },
        ];
    }
    
    public function validateRecord($data)
    {
        $errors = [];
        
        $data['email'] = trim($data['email']);
        if (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
            $errors['email'] = Yii::t('app', "Неверный формат E-mail");
        } else {
            $check_query = self::find()
                ->select(['id'])
                ->where([
                    'deleted' => 0,
                    'email' => $data['email'],
                ])
                ->limit(1);
            if (!empty($data['id'])) {
                $check_query->andWhere("id != " . $data['id']);
            }
            $check = $check_query->one();
            if (!empty($check)) {
                $errors['email'] = Yii::t('app', "Такой E-mail уже используеся");
            }
        }
        
        $data['password'] = trim($data['password']);
        $data['password_confirm'] = trim($data['password_confirm']);
        
        if (empty($data['id'])) {
            if (empty($data['password'])) {
                $errors['password'] = Yii::t('app', "Введите Пароль");
            }
        }
        
        if (!empty($data['password'])) {
            if (strlen($data['password']) < self::$password_rules['min_chars'] || strlen($data['password']) > self::$password_rules['max_chars']) {
                $errors['password'] = Yii::t('app', "Пароль должен содержать от {min} до {max} символов", [
                    'min' => self::$password_rules['min_chars'],
                    'max' => self::$password_rules['max_chars'],
                ]);
            }
            
            if (empty($data['password_confirm'])) {
                $errors['password_confirm'] = Yii::t('app', "Введите Подтверждение пароля");
            } else {
                if ($data['password_confirm'] !== $data['password']) {
                    $errors['password_confirm'] = Yii::t('app', "Неверное подтверждение пароля");
                }
            }
        }
        
        $data['login'] = trim($data['login']);
        if (!preg_match(self::$login_rules['regexp'], $data['login'])) {
            $errors['login'] = Yii::t('app', "Никнейм должен состоять из латинских букв, цыфр, '.', '_', '-' (от {min} до {max} символов)", [
                'min' => self::$login_rules['min_chars'],
                'max' => self::$login_rules['max_chars'],
            ]);
        } else {
            $check_query = self::find()
                ->select(['id'])
                ->where([
                    'deleted' => 0,
                    'login' => $data['login'],
                ])
                ->limit(1);
            if (!empty($data['id'])) {
                $check_query->andWhere("id != " . $data['id']);
            }
            $check = $check_query->one();
            if (!empty($check)) {
                $errors['login'] = Yii::t('app', "Такой Никнейм уже используеся");
            }
        }
        
        $data['first_name'] = trim($data['first_name']);
        if (empty($data['first_name'])) {
            $errors['first_name'] = Yii::t('app', "Заполните Имя");
        } else {
            if (!preg_match(self::$name_rules['regexp'], $data['first_name'])) {
                $errors['first_name'] = Yii::t('app', "Имя должно состоять из букв (от {min} до {max} символов)", [
                    'min' => self::$name_rules['min_chars'],
                    'max' => self::$name_rules['max_chars'],
                ]);
            }
        }
        
        $data['second_name'] = trim($data['second_name']);
        if (!empty($data['second_name'])) {
            if (!preg_match(self::$name_rules['regexp'], $data['second_name'])) {
                $errors['second_name'] = Yii::t('app', "Отчество должно состоять из букв (от {min} до {max} символов)", [
                    'min' => self::$name_rules['min_chars'],
                    'max' => self::$name_rules['max_chars'],
                ]);
            }
        }
        
        $data['last_name'] = trim($data['last_name']);
        if (empty($data['last_name'])) {
            $errors['last_name'] = Yii::t('app', "Заполните Фамилию");
        } else {
            if (!preg_match(self::$name_rules['regexp'], $data['last_name'])) {
                $errors['last_name'] = Yii::t('app', "Фамилия должна состоять из букв (от {min} до {max} символов)", [
                    'min' => self::$name_rules['min_chars'],
                    'max' => self::$name_rules['max_chars'],

backend/views/layouts/datepicker.php
<?php

/**
 * Datepicker input
 * 
 * @var $name string
 * @var $value string|integer
 * @var $time boolean
 * @var $readonly boolean default false
 * @var $onclick string
 * @var $onchange string
 * @var $class string
 */

if (is_numeric($value)) {
    $value = date(Yii::$app->params['date_time_format'], $value);
}
$readonly_string = ($readonly === true ? 'readonly' : '');

$replacements = [
    '][' => '_', 
    '[' => '_', 
    ']' => '',
];

if ($time === true) {
    $date_name = $name . '[date]';
    $date_id = str_replace(array_keys($replacements), array_values($replacements), $name) . '_date';
    $hour_name = $name . '[hour]';
    $hour_id = str_replace(array_keys($replacements), array_values($replacements), $name) . '_hour';
    $minute_name = $name . '[minute]';
    $minute_id = str_replace(array_keys($replacements), array_values($replacements), $name) . '_minute';
    
    if (!empty($value)) {
        $time_value = end(explode(' ', $value));
        $time_value = explode(':', $time_value);
        if (!empty($time_value[0])) {
            $this->params['js_code'][] = '$("#' . $hour_id . '").val("' . $time_value[0] . '");';
        }
        if (!empty($time_value[1])) {
            $this->params['js_code'][] = '$("#' . $minute_id . '").val("' . $time_value[1] . '");';
        }
        $value = reset(explode(' ', $value));
    }
} else {
    $date_name = $name;
    $date_id = str_replace(array_keys($replacements), array_values($replacements), $name);
}

if ($readonly !== true) {
    $this->params['js_code'][] = '$("#' . $date_id . '").datepicker({
        dateFormat: "yy-mm-dd"
    });';
}

$events = [];
if (!empty($onchange)) {
    $events[] = 'onchange="' . $onchange . '"';
}
if (!empty($onclick)) {
    $events[] = 'onclick="' . $onclick . '"';
}
$events = implode(' ', $events);

?>

<div class="has-feedback" style="display:inline-block;">
    <input type="text" name="<?= $date_name ?>" id="<?= $date_id ?>" value="<?= $value ?>" class="form-control <?= ($class ?? '') ?>" <?= $events ?> <?= $readonly_string ?> style="padding-left:6px; padding-right:40px; width:120px; display:inline-block">
    <span class="fa fa-calendar form-control-feedback right" aria-hidden="true" style="right:0;"></span>
</div>
<?php if ($time === true) { ?>
    <select name="<?= $hour_name ?>" id="<?= $hour_id ?>" class="form-control <?= ($class ?? '') ?>" <?= $events ?> <?= $readonly_string ?> style="width:60px; display:inline-block">
        <option value="">-</option>
        <?php for ($i = 0; $i < 24; $i++) {
            echo '<option value="' . ($i < 10 ? str_pad($i, 2, '0', STR_PAD_LEFT) : $i) . '">' . ($i < 10 ? str_pad($i, 2, '0', STR_PAD_LEFT) : $i) . '</option>';
        } ?>
    </select> : 
    <select name="<?= $minute_name ?>" id="<?= $minute_id ?>" class="form-control <?= ($class ?? '') ?>" <?= $events ?> <?= $readonly_string ?> style="width:60px; display:inline-block">
        <option value="">-</option>
        <?php for ($i = 0; $i < 60; $i++) {
            echo '<option value="' . ($i < 10 ? str_pad($i, 2, '0', STR_PAD_LEFT) : $i) . '">' . ($i < 10 ? str_pad($i, 2, '0', STR_PAD_LEFT) : $i) . '</option>';
        } ?>
    </select>
<?php } ?>

backend/views/layouts/delete.php
<?php

use Yii;

if (empty($action)) {
    $action = 'list';
}

?>

<?php if (!empty($data)) { ?>
    <?php if (!empty($warning)) { ?>
        <div class="alert alert-warning" role="alert">
            <span class="glyphicon glyphicon-warning-sign"></span>
            <?= $warning ?>
        </div>
    <?php } ?>
    <form id="record_form" method="post" enctype="multipart/form-data">
        <?= $this->render('/layouts/form') ?>
        <input type="hidden" name="delete" id="delete" value="1">
        <p><?= Yii::t('app', 'Удалить эту запись?') ?></p>
        <button type="submit" id="submit_button" class="btn btn-danger"><?= Yii::t('app', 'Удалить') ?></button>
        <a href="<?= \yii\helpers\Url::to(Yii::$app->params['urls']['backend'] . Yii::$app->controller->id . '/' . $action) ?>" class="btn btn-default cancel_button"><?= Yii::t('app', 'Отменить') ?></a>
    </form>
<?php } else { ?>
    <?= $this->render('/layouts/record_not_found') ?>
<?php } ?>

backend/views/layouts/export.php
<?php

use Yii;
use app\library\Export;

?>

<div class="col-md-9">
    <p><?= Yii::t('app', 'Для фильтрации экспортируемых данных используются результаты поиска в соответствующем разделе') ?></p>
    <form id="export_form" method="post" enctype="multipart/form-data">
        <?= $this->render('/layouts/form') ?>
        <div class="form-group">
            <label for="format"><?= Yii::t('app', 'Формат экспорта') ?></label>
            <select name="format" id="format" class="form-control">
            <?php foreach (Export::$available_formats as $item) { ?>
                <option value="<?= $item ?>"><?= $item ?></option>
            <?php } ?>
            </select>
        </div>
        <?php if (!empty($include)) { ?>
            <?= $this->render($include) ?>
        <?php } ?>
        <hr>
        <div class="form-group">
            <button type="submit" id="submit_button" class="btn btn-primary"><?= Yii::t('app', 'Экспортировать') ?></button>
            <a href="<?= \yii\helpers\Url::to(Yii::$app->params['urls']['backend'] . Yii::$app->controller->id . '/' . (!empty($link) ? $link : 'list')) ?>" class="btn btn-default cancel_button"><?= Yii::t('app', 'Отменить') ?></a>
        </div>
    </form>
</div>

backend/views/layouts/form.php
<?php

?>
<input name="_csrf" id="_csrf" value="<?= Yii::$app->request->csrfToken ?>" type="hidden">

backend/views/layouts/html_editor.php
<?php

$controls = [
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'style',
    '|',
    'bullets',
    'numbering',
    '|',
    'alignleft',
    'center',
    'alignright',
    'justify',
    '|',
    'undo',
    'redo',
    '|',
    'rule',
    'image',
    'link',
    'unlink',
    '|',
    'cut',
    'copy',
    'paste',
    'pastetext',
    '|',
    'source',
];

$id = str_replace(['][', '[', ']'], ['_', '_', ''], $name);
$this->params['js_code'][] = 'var editor_' . $id . ' = $("#' . $id . '").cleditor({
        controls: // controls to add to the toolbar
            "' . implode(' ', $controls) . '"
    });
    if (!html_editors) {
        var html_editors = {};
    }
    
    html_editors["' . $id . '"] = editor_' . $id . '[0];';

?>

<textarea name="<?= $name ?>" id="<?= $id ?>" class="jqte-test" style="display:none;"><?= $value ?></textarea>

backend/views/layouts/image_cropper.php
<?php

use Yii;

$this->params['js_code'][] = 'getImageForCropper("' . $name . '");';

?>

<label class="control-label" for="<?= $name ?>_image"><?= Yii::t('app', 'Image') ?></label><br>
<?php if (!empty($file)) { ?>
    <img src="<?= $file ?>?t=<?= time() ?>" alt="<?= $name ?>" class="thumbnail">
    <div class="checkbox">
        <label>
            <input type="checkbox" name="<?= $name ?>[delete]" id="<?= $name ?>_delete" value="1"> 
            <?= Yii::t('app', 'delete image') ?>
        </label>
    </div>
<?php } ?>
<input type="file" name="<?= $name ?>[image]" id="<?= $name ?>_image" />
<div class="crop_image_box">
    <img id="<?= $name ?>_preview" accept="image/x-png,image/gif,image/jpeg" style="">
</div>

<input type="hidden" name="<?= $name ?>[x]" id="<?= $name ?>_x1" value="">
<input type="hidden" name="<?= $name ?>[y]" id="<?= $name ?>_y1" value="">
<input type="hidden" name="<?= $name ?>[width]" id="<?= $name ?>_w" value="">
<input type="hidden" name="<?= $name ?>[height]" id="<?= $name ?>_h" value="">

backend/views/layouts/loading.php
<?php

?>

<div class="loading_box">
    <img src="/images/loading.gif" alt="" />
</div>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use Yii;
use app\models\Users;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

if (!empty(Yii::$app->session->get('auth'))) {
    $this->params['js_code'][] = "checkUserActivity();";
    $this->params['js_code'][] = "$('#menu_toggle').click(storeMenuState)";
    if (Users::checkAccessPermissions('chat', 'index') === true) {
        $this->params['js_code'][] = "chackNewChatMessages();";
        $this->params['js_code'][] = "setInterval(chackNewChatMessages, 10000);";
    }
    if (Users::checkAccessPermissions('recommendations', 'list') === true) {
        $this->params['js_code'][] = "chackNewRecommendations();";
        $this->params['js_code'][] = "setInterval(chackNewRecommendations, 10000);";
    }
}
$this->params['js_code'][] = "expandMenuSection('" . Yii::$app->controller->id . "')";

$backend_menu_state = Yii::$app->session->get('backend_menu_state');

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="/images/icons/Favicon_16px.png">
</head>
<body class="<?= (empty($backend_menu_state) || $backend_menu_state == 'opened' ? 'nav-md' : 'nav-sm') ?>">
<?php $this->beginBody() ?>
    <div class="container body">
        <div class="main_container">
            <?php if (Yii::$app->controller->id == 'auth' && Yii::$app->controller->action->id == 'login') { ?>
                <div class="col-md-12">
                    <?= $content ?>
                </div>
            <?php } else { ?>
            <!-- left column -->
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="<?= Url::to(Yii::$app->params['urls']['backend']) ?>" class="site_title"><span><?= Yii::$app->params['projectName'] ?></span></a>
                    </div>

                    <div class="clearfix"></div>

                    <?php if (!empty(Yii::$app->session->get('auth'))) { ?>
                    <div class="profile clearfix">
                        <div class="profile_info">
                            <span><?= Yii::t('app', 'Добро пожаловать') ?>,</span>
                            <h2><?= Yii::$app->session->get('auth')['name'] ?></h2>
                        </div>
                    </div>
                    
                    <br />

                    <!-- Menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li>
                                    <a href="<?= Url::to(Yii::$app->params['urls']['backend']) ?>">
                                        <i class="fa fa-home"></i> <?= Yii::t('app', 'Стартовая') ?>
                                    </a>
                                </li>
                            </ul>
                            <?php if (!empty(Yii::$app->params['menu'])) { ?>
                                <?php foreach (Yii::$app->params['menu'] as $menu_controller) { ?>
                                    <ul class="nav side-menu">
                                        <li id="menu_<?= $menu_controller['url'] ?>">
                                            <a>
                                                <i class="fa <?= $menu_controller['class'] ?>"></i> 
                                                <?= $menu_controller['name'] ?>
                                                <span class="fa fa-chevron-down"></span>
                                            </a>
                                            <ul class="nav child_menu">
                                            <?php foreach ($menu_controller['actions'] as $menu_action) { ?>
                                                <?php $url = Url::to(Yii::$app->params['urls']['backend'] . $menu_controller['url'] . '/' . $menu_action['url']); ?>
                                                <?php if ($menu_action['display'] == true) { ?>
                                                    <li><a href="<?= $url ?>"><?= $menu_action['name'] ?></a></li>
                                                <?php } ?>
                                            <?php } ?>
                                            </ul>
                                        </li>
                                    </ul>        
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <!-- END Left column -->
        
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <?php if (!empty(Yii::$app->session->get('auth'))) { ?>
                        <ul id="top_right_info_box" class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <?= Yii::$app->session->get('auth')['name'] ?>
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="<?= Url::to(Yii::$app->params['urls']['backend'] . 'auth/password') ?>"><i class="fa fa-lock pull-right"></i> <?= Yii::t('app', 'Сменить пароль') ?></a></li>
                                    <li><a href="<?= Url::to(Yii::$app->params['urls']['backend'] . 'auth/logout') ?>"><i class="fa fa-sign-out pull-right"></i> <?= Yii::t('app', 'Выйти') ?></a></li>
                                </ul>
                            </li>
                            <li class="dropdown clock_box" title="<?= Yii::t('app', 'Server time') ?>">
                                <span id="hours"><?= date('H', time()) ?></span>
                                :
                                <span id="min"><?= date('i', time()) ?></span>
                                :
                                <span id="sec"><?= date('s', time()) ?></span>
                                <small><?= date_default_timezone_get() ?></small>
                            </li>
                            <li id="header_alert_box" class="dropdown header_alert_box">
                                <?php if (Users::checkAccessPermissions('chat', 'index') === true) { ?>
                                <span id="header_alert_chat_new_messages_box" class="badge header_alert">
                                    <a href="<?= Url::to(Yii::$app->params['urls']['backend'] . 'chat/index') ?>" title="<?= Yii::t('app', 'Новые сообщения в чате') ?>">
                                        <span class="fa fa-pencil"></span>
                                        <span id="header_alert_chat_new_messages">0</span>
                                    </a>
                                </span>
                                <?php } ?>
                                <?php if (Users::checkAccessPermissions('recommendations', 'list') === true) { ?>
                                <span id="header_alert_new_recommendations_box" class="badge header_alert">
                                    <a href="<?= Url::to(Yii::$app->params['urls']['backend'] . 'recommendations/list?new=1') ?>" title="<?= Yii::t('app', 'Новые заявки') ?>">
                                        <span class="fa fa-money"></span>
                                        <span id="header_alert_new_recommendations">0</span>
                                    </a>
                                </span>
                                <?php } ?>
                            </li>
                        </ul>
                        <?php } ?>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <?= $this->render('/layouts/alerts') ?>
                <?= Breadcrumbs::widget([
                    'homeLink' => [
                        'label' => Yii::t('app', 'Стартовая'), 
                        'url' => yii\helpers\Url::to(Yii::$app->params['urls']['backend'])
                    ],
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
                <?= $content ?>
                <div class="bottom_delimiter"></div>
                <br>
            </div>
            
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    <p class="pull-left">&copy; <?= Yii::$app->params['projectName'] ?> <?= date('Y') ?></p>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
            <?php } ?>
        </div>
    </div>
    
    <div id="dictionary_entries" style="display:none;">
        <span id="server_error"><?= Yii::t('app', 'Server error') ?></span>
        <span id="success"><?= Yii::t('app', 'Success') ?></span>
        <span id="success_operation"><?= Yii::t('app', 'Data was saved successfully') ?></span>
    </div>
        
    <form id="sort_form" method="post" style="display:none;">
        <?= $this->render('/layouts/form') ?>
        <input type="hidden" name="sort" id="sort" value="">
    </form>
    
    <?php $this->endBody() ?>
    
    <?php if (!empty($this->params['js_code'])) { ?>
        <?= "\n" . '<script>' ?>
        <?php foreach ($this->params['js_code'] as $js_code) { ?>
            <?= "\n" . $js_code ?>
        <?php } ?>
        <?= "\n" . '</script>' ?>
    <?php } ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/pager.php
<?php

use yii\widgets\LinkPager;

?>

<?= LinkPager::widget([
    'pagination' => $pages,
    'nextPageLabel' => '&rsaquo;',
    'prevPageLabel' => '&lsaquo;',
    'firstPageLabel' => '&laquo;',
    'lastPageLabel' => '&raquo;',
]); ?>

backend/views/layouts/record_not_found.php
<?php 

use Yii;

?>

<?= Yii::t('app', 'Запись не найдена') ?>

backend/views/layouts/sort.php
<?php

$sort = 'ASC';
if (!empty(Yii::$app->params['sort'])) {
    $current_field = reset(explode(' ', Yii::$app->params['sort']));
    if ($current_field == $field) {
        $current_sort = end(explode(' ', Yii::$app->params['sort']));
        $sort = ($current_sort == 'ASC' ? 'DESC' : 'ASC');
    }
}

?>

<a href="javascript:void(0);" onclick="changeSort('<?= $field ?> <?= $sort ?>');" title="Change sort by '<?= $label ?>'">
    <?= $label ?>
    <?php if (!empty($current_sort)) { ?>
        <span class="glyphicon glyphicon-chevron-<?= ($current_sort == 'ASC' ? 'up' : 'down') ?>"></span>
    <?php } ?>
</a>

backend/views/layouts/time.php
<?php 

use Yii;

?>

<?php if (!empty($field)) { ?>
     <?= date(Yii::$app->params['date_time_format'], $field); ?>
<?php } ?>